export interface User {
  id: string;
  name: string;
  email: string;
  passwordHash: string;
  isApproved: boolean;
  role: 'user' | 'trainer';
  paymentPending?: boolean;
  referralCode?: string; // Legacy static code (optional now)
  instituteName?: string;
  instituteLocation?: string;
  
  // Web Dashboard & Referral Logic
  walletBalance: number;
  referralCount: number;
  subscriptionExpiry: string; // ISO Date string
  referralLink: string; // Keeping for backward compatibility or static link
  
  // Dynamic Code Logic
  activeReferralCode?: string;     // The code currently generated by this trainer
  referralCodeExpiry?: number;     // Timestamp (ms) when code expires
  usedReferralCode?: string;       // The code this user used when signing up
}

export enum AppView {
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
  SIGNUP_USER = 'SIGNUP_USER',
  SIGNUP_TRAINER = 'SIGNUP_TRAINER',
  PAYMENT = 'PAYMENT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  DASHBOARD = 'DASHBOARD', // The Extension Overlay
  WEB_DASHBOARD = 'WEB_DASHBOARD', // The User Website Dashboard
  USER_SUCCESS = 'USER_SUCCESS', // The User Post-Login Screen
}

export interface Product {
  asin: string;
  title: string;
  brand: string;
  price: number;
  rating: number;
  reviewCount: number;
  imgUrl: string;
  sellers: number;
  stockStatus: 'In Stock' | 'Low Stock' | 'Out of Stock';
  bsr: number;
  estSales: number;
  revenue: number;
  fees: number;
}

export interface MarketplaceComparison {
  name: string;
  price: number;
  url: string;
  logo: string;
  shipping: string;
}

export interface SortConfig {
  key: keyof Product | null;
  direction: 'asc' | 'desc';
}

export interface Referral {
  id: string;
  name: string;
  date: string;
  status: 'Completed' | 'Pending';
  commission: number;
}